openapi: 3.1.0
info:
  title: Authorization
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
  parameters:
    bearer:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      description: Bearer <token>
