openapi: 3.1.0
info:
  summary: お気に入り関連API
  title: お気に入りAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /favorites/:
    get:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  test:
                    type: string
                  arr:
                    type: array
                    items:
                      type: object
                      properties:
                        aaa:
                          type: string
          description: お気に入り成功
      summary: お気に入り一覧を取得する
      tags: []
    parameters: []
    post:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  test:
                    type: string
                  arr:
                    type: array
                    items:
                      type: object
                      properties:
                        aaa:
                          type: string
          description: お気に入り成功
        '400':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
          description: リクエスト不正
      summary: お気に入り登録する
      tags: []
  '/favorites/{id}':
    delete:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  test:
                    type: string
                  arr:
                    type: array
                    items:
                      type: object
                      properties:
                        aaa:
                          type: string
          description: お気に入り成功
        '400':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
          description: リクエスト不正
        '404':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    errors:
                      - code: string
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
          description: お気に入りデータが存在しない
      summary: お気に入り削除する
      tags: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
