openapi: 3.1.0
info:
  title: 予約状態API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /reserves/sure:
    parameters: []
    post:
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    test: string
                    aaa:
                      - tttt: string
                        hoge: string
              schema:
                type: object
                properties:
                  test:
                    type: string
                  aaa:
                    type: array
                    items:
                      type: object
                      properties:
                        tttt:
                          type: string
                        hoge:
                          type: string
          description: 予約状態成功
        '400':
          content:
            application/json:
              examples: {}
              schema: {}
          description: リクエスト不正
        '404':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 予約状態データが存在しない
      summary: 予約状態を確定する
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      description: ''
      parameters:
        - $ref: ./common/Authorization.yaml#/components/parameters/bearer
  '/reserves/{id}':
    get:
      responses:
        '200':
          content:
            application/json:
              examples:
                example-1: {}
              schema: {}
          description: 予約状態成功
        '400':
          content:
            application/json:
              examples: {}
              schema: {}
          description: リクエスト不正
        '404':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 予約状態データが存在しない
      summary: 予約状態を取得する
      tags: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    put:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  test:
                    type: string
                  arr:
                    type: array
                    items:
                      type: object
                      properties:
                        aaa:
                          type: string
          description: 予約状態成功
        '400':
          content:
            application/json:
              examples: {}
              schema:
                type: object
                properties:
                  test:
                    type: string
          description: リクエスト不正
        '404':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 予約状態データが存在しない
      summary: 予約状態を更新する
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  type: string
                arr:
                  type: array
                  items:
                    type: object
                    properties:
                      aaa:
                        type: string
