openapi: 3.1.0
info:
  title: 店舗情報API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /stores/:
    get:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 店舗情報成功
      summary: 店舗情報一覧を取得する
      tags: []
    parameters: []
  /stores/search:
    get:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 店舗情報成功
        '400':
          content:
            application/json:
              examples: {}
              schema: {}
          description: リクエスト不正
      summary: 店舗情報を検索する
      tags: []
    parameters: []
  '/stores/{id}':
    get:
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 店舗情報成功
        '400':
          content:
            application/json:
              examples:
                example-1:
                  value:
                    errors:
                      - code: string
              schema:
                $ref: ./common/ErrorResponse.yaml
          description: リクエスト不正
        '404':
          content:
            application/json:
              examples: {}
              schema: {}
          description: 店舗情報データが存在しない
      summary: 店舗情報を取得する
      tags: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
